name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rye
        uses: sksat/setup-rye@v0.1.0

      - name: Install Python Library
        run: rye sync

      - name: Lint
        run: rye run lint

      - name: Test
        run: rye run test

      - name: Build
        run: rye build
